# Generated by Django 6.0 on 2025-12-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('intro_titre', models.CharField(max_length=255)),
                ('intro_texte', models.TextField()),
                ('def_titre', models.CharField(max_length=255)),
                ('def_texte', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='bureautique.cours')),
            ],
        ),
        migrations.CreateModel(
            name='PartiePrincipale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_principales', to='bureautique.etape')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminee', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureautique.etape')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('modal_type', models.CharField(blank=True, max_length=50)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_objets', to='bureautique.etape')),
            ],
        ),
        migrations.CreateModel(
            name='Utilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilites', to='bureautique.etape')),
            ],
        ),
    ]
