# Generated by Django 6.0 on 2025-12-20 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressionutilisateur',
            name='etape',
        ),
        migrations.AddField(
            model_name='cours',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressionutilisateur',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bureautique.cours'),
            preserve_default=False,
        ),
    ]
