# Generated by Django 6.0 on 2025-12-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0002_remove_progressionutilisateur_etape_cours_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressionutilisateur',
            old_name='terminee',
            new_name='is_started',
        ),
    ]
