# Generated by Django 6.0 on 2025-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0003_rename_terminee_progressionutilisateur_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionutilisateur',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
