# Generated by Django 6.0 on 2025-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0004_progressionutilisateur_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
