# Generated by Django 6.0 on 2025-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0005_cours_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
