# Generated by Django 6.0 on 2025-12-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureautique', '0006_alter_cours_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='slug',
        ),
    ]
